# Roboto Mono with its vertical metrics evened out, so the text caret (which spans the font's ascent + descent)
# sticks out as far above the capitals as below the baseline: centered on them, like the system font's caret.
# The total stays the same, so line heights don't change; the text sits ~0.03em higher, capitals centered in the line.
# Safari has no ascent-override/descent-override, so the fix has to be in the files.
#
# Regenerate (after updating @fontsource-variable/roboto-mono): pip install fonttools brotli; python scripts/patch-font.py
import re
from pathlib import Path
from fontTools.ttLib import TTFont

SRC = Path("node_modules/@fontsource-variable/roboto-mono")
OUT = Path("src/assets/fonts")
OUT.mkdir(parents=True, exist_ok=True)

css = ""
for sheet in ["index.css", "wght-italic.css"]:
    text = (SRC / sheet).read_text()
    for name in re.findall(r"url\(\./files/([^)]+)\)", text):
        font = TTFont(SRC / "files" / name)
        hhea, os2 = font["hhea"], font["OS/2"]
        total = hhea.ascent - hhea.descent  # 2146 + 555
        descent = (total - os2.sCapHeight) // 2  # as much room under the baseline as over the capitals
        ascent = total - descent
        hhea.ascent, hhea.descent, hhea.lineGap = ascent, -descent, 0
        os2.sTypoAscender, os2.sTypoDescender, os2.sTypoLineGap = ascent, -descent, 0
        os2.usWinAscent, os2.usWinDescent = ascent, descent
        os2.fsSelection |= 1 << 7  # USE_TYPO_METRICS: every platform reads the same numbers
        font.save(OUT / name)
    css += text.replace("./files/", "./assets/fonts/")

Path("src/fonts.css").write_text(
    "/* Generated by scripts/patch-font.py: @fontsource-variable/roboto-mono with evened-out vertical metrics. */\n" + css
)
print(f"ascent {ascent}, descent {descent}")
